watch_me/account/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    path('welcome/', views.welcome, name="welcome"),
    path('profile/', views.profile, name="profile"),
    path('register/', views.sign_up, name="register"),
    path('login/', views.sign_in, name="login"),
    path('logout/', views.sign_off, name="logout"),
    path('edit-profile/', views.edit_profile, name="edit_profile"),
    path('user/<username>/', views.user_profile, name="user_profile"),
    path('follow/<username>/', views.follow, name="follow"),
    path('unfollow/<username>/', views.unfollow, name="unfollow"),
]

watch_me/posts/urls.py
from django.urls import path
from . import views

app_name = "posts"

urlpatterns = [
    path('', views.home, name='home'),
    path('create-post/', views.create_post, name='create_post'),
    path('like/<int:pk>', views.like, name="like"),
    path('unlike/<int:pk>', views.unlike, name="unlike"),
]

watch_me/watch_me/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.redirect),
    path('account/', include('account.urls')),
    path('posts/', include('posts.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

watch_me/posts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='post')
    image = models.ImageField(upload_to='post_images')
    caption = models.CharField(max_length=264, blank=True)
    upload_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-upload_date']

    def __str__(self):
        return f"{self.author} : {self.caption}"

class Like(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='liked_post')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='liker')
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.post} : {self.user}"

watch_me/posts/forms.py
from django import forms
from .models import Post

class CreatePostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('image', 'caption')

watch_me/posts/views.py
from django.shortcuts import render, reverse
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from .forms import CreatePostForm
from account.models import UserProfile, Follow
from django.contrib.auth.models import User
from .models import Post, Like

# Create your views here.

@login_required
def home(request):
    if request.method == "GET":
        search = request.GET.get('search', '')
        result = User.objects.filter(username__icontains=search)

    following_list = Follow.objects.filter(follower=request.user)
    posts = Post.objects.filter(author__in=following_list.values_list('following'))

    liked_post = Like.objects.filter(user=request.user)
    liked_post_list = liked_post.values_list('post', flat=True)

    context = {'search': search, 'result': result, 'posts': posts, 'liked_post_list': liked_post_list}
    return render(request, 'posts/home.html', context=context)

@login_required
def create_post(request):
    form = CreatePostForm()

    if request.method == "POST":
        form = CreatePostForm(request.POST, request.FILES)

        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            form.save()
            return HttpResponseRedirect(reverse('posts:home'))

    context = {'form': form}
    return render(request, 'posts/create_post.html', context=context)

@login_required
def like(request, pk):
    post = Post.objects.get(pk=pk)
    already_liked = Like.objects.filter(post=post, user=request.user)
    if not already_liked:
        liked_post = Like(post=post, user=request.user)
        liked_post.save()
    return HttpResponseRedirect(reverse('posts:home'))

@login_required
def unlike(request, pk):
    post = Post.objects.get(pk=pk)
    already_liked = Like.objects.filter(post=post, user=request.user)
    already_liked.delete()
    return HttpResponseRedirect(reverse('posts:home'))

watch_me/templates/posts/create_post.html
{% extends 'base_nav.html' %}
{% block title %} Create post {% endblock %}
{% load crispy_forms_tags %}

{% block css %}

{% endblock %}

{% block body %}
<h1>Create post!</h1>
<form method="POST" enctype="multipart/form-data">
    {{ form|crispy }}
    {% csrf_token %}
    <input type="submit" name="submit" value="Add post" class="btn btn-success">
</form>

{% endblock %}

watch_me/templates/posts/home.html
{% extends 'base_nav.html' %}
{% block title %} Posts {% endblock %}
{% load crispy_forms_tags %}

{% block css %}

{% endblock %}

{% block body %}

<hr>
{% if search %}


        {% for user in result %}
        <div class="row">
            <div class="col-sm-2">

                {% if user.user_profile.profile_pic %}
                    <a href="{% url 'account:user_profile' username=user.username %}"> <img src="/media/{{ user.user_profile.profile_pic }}" width=80px height=80px class="rounded-circle"> </a>
                {% else %}
                    <a href="{% url 'account:user_profile' username=user.username %}"> <img src="/media/profile_pics/blank.png" width=80px height=80px class="rounded-circle"> </a>
                {% endif %}

            </div>

            <div class="col-sm-10">
                <h6>{{ user.username }}</h6>
                {{ user.user_profile.full_name }}
            </div>
        </div>
        <hr>
        {% endfor %}
 

{% else %}

{% for post in posts %}
<div class="row">
    <div class="col-sm-8" style="padding:10px; margin:10px;">
        {% if post.author.user_profile.profile_pic %}
            <img src="/media/{{ post.author.user_profile.profile_pic }}" width=50px height=50px class="rounded-circle">
        {% else %}
            <img src="/media/profile_pics/blank.png" width=50px height=50px class="rounded-circle">
        {% endif %} 
        &nbsp;
        <b><a href="{% url 'account:user_profile' username=post.author.username %}">{{ post.author.username }}</a></b>
    </div>
    <div class="col-sm-8" style="padding:0 0 0 10px; margin:0 0 0 10px;">
        <h2>{{ post.caption }}</h2>
    </div>
    <div class="col-sm-8" style="padding:10px; margin:10px;">
        <img src="/media/{{ post.image }}">
        <br>
        {% if post.pk not in liked_post_list %}
        <a href="{% url 'posts:like' pk=post.pk %}">LIKE</a>
        {% else %}
        <a href="{% url 'posts:unlike' pk=post.pk %}">UNLIKE</a>
        {% endif %}
    </div>
</div>
<br>
{% endfor %}


{% endif %}
{% endblock %}