watch_me/account/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    path('welcome/', views.welcome, name="welcome"),
    path('profile/', views.profile, name="profile"),
    path('register/', views.sign_up, name="register"),
    path('login/', views.sign_in, name="login"),
    path('logout/', views.sign_off, name="logout"),
    path('edit-profile/', views.edit_profile, name="edit_profile"),
    path('user/<username>/', views.user_profile, name="user_profile"),
    path('follow/<username>/', views.follow, name="follow"),
    path('unfollow/<username>/', views.unfollow, name="unfollow"),
]

watch_me/posts/urls.py
from django.urls import path
from . import views

app_name = "posts"

urlpatterns = [
    path('', views.home, name='home'),
    path('create-post/', views.create_post, name='create_post'),
    path('like/<int:pk>', views.like, name="like"),
    path('unlike/<int:pk>', views.unlike, name="unlike"),
]

watch_me/watch_me/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.redirect),
    path('account/', include('account.urls')),
    path('posts/', include('posts.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

watch_me/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    
    <title>
        {% block title %} {% endblock %}
    </title>

    {% block css %} {% endblock %}
    
  </head>
  <body>

    <div class="container" style="margin-top: 20px;">
        {% block body %}
        {% endblock %}
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
    -->
  </body>
</html>

watch_me/templates/base_nav.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    
    <title>
        {% block title %} {% endblock %}
    </title>

    {% block css %}
    
    {% endblock %}

    <style>
      body{
        background-color: rgba(40, 26, 121, 0.349);
      }
      .formul{
     display:inline;
     margin:0px;
     padding:0px;
      }
    </style>
    
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'posts:home' %}">Watch me!</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">

              {% if user.is_authenticated %}

                <form class="d-flex" method="GET">
                  <input class="form-control mr-sm-2" type="text" name="search" placeholder="Search">
                  <button class="btn btn-success" type="submit">Search</button>
                </form>

                <li class="nav-item">
                  <a class="nav-link" href="{% url 'posts:create_post' %}">Add post</a>
                </li>

                <li class="nav-item">
                  <a class="nav-link" href="{% url 'account:profile' %}">Profile</a>
                </li>

                <li class="nav-item">
                  <a class="nav-link" href="{% url 'account:logout' %}">Logout</a>
                </li> 

                {% if user.user_profile.profile_pic %}

                  <a href="#"> <img src="/media/{{ user.user_profile.profile_pic }}" width=30px height=30px class="rounded-circle"> </a>

                {% else %}

                  <a href="#"> <img src="/media/profile_pics/blank.png" width=30px height=30px class="rounded-circle"> </a>

                {% endif %}

              {% else %}

                <li class="nav-item">
                  <a class="nav-link" href="{% url 'account:login' %}">Login</a>
                </li>

                <li class="nav-item">
                  <a class="nav-link" href="{% url 'account:register' %}">Register</a>
                </li>

              {% endif %}

            </ul>
          </div>
        </div>
    </nav>

    <div class="container" style="margin-top: 20px;">
        {% block body %}
        {% endblock %}
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
    -->
  </body>
</html>